package pojo;
// Generated 21 juin 2021 11:06:58 by Hibernate Tools 4.3.1

import hibernateUtile.NewHibernateUtil;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;




/**
 * Covid generated by hbm2java
 */
public class Covid  implements java.io.Serializable {


     private Integer id;
     private String isoCode;
     private String continent;
     private String location;
     private String date;
     private String totalCases;
     private String newCases;
     private String newCasesSmoothed;
     private String totalDeaths;
     private String newDeaths;
     private String newDeathsSmoothed;
     private String totalCasesPerMillion;
     private String newCasesPerMillion;
     private String newCasesSmoothedPerMillion;
     private String totalDeathsPerMillion;
     private String newDeathsPerMillion;
     private String newDeathsSmoothedPerMillion;
     private String reproductionRate;
     private String icuPatients;
     private String icuPatientsPerMillion;
     private String hospPatients;
     private String hospPatientsPerMillion;
     private String weeklyIcuAdmissions;
     private String weeklyIcuAdmissionsPerMillion;
     private String weeklyHospAdmissions;
     private String weeklyHospAdmissionsPerMillion;
     private String newTests;
     private String totalTests;
     private String totalTestsPerThousand;
     private String newTestsPerThousand;
     private String newTestsSmoothed;
     private String newTestsSmoothedPerThousand;
     private String positiveRate;
     private String testsPerCase;
     private String testsUnits;
     private String totalVaccinations;
     private String peopleVaccinated;
     private String peopleFullyVaccinated;
     private String newVaccinations;
     private String newVaccinationsSmoothed;
     private String totalVaccinationsPerHundred;
     private String peopleVaccinatedPerHundred;
     private String peopleFullyVaccinatedPerHundred;
     private String newVaccinationsSmoothedPerMillion;
     private String stringencyIndex;
     private String population;
     private String populationDensity;
     private String medianAge;
     private String aged65Older;
     private String aged70Older;
     private String gdpPerCapita;
     private String extremePoverty;
     private String cardiovascDeathRate;
     private String diabetesPrevalence;
     private String femaleSmokers;
     private String maleSmokers;
     private String handwashingFacilities;
     private String hospitalBedsPerThousand;
     private String lifeExpectancy;
     private String humanDevelopmentIndex;
     private String excessMortality;

    public Covid() {
    }

    public Covid(String isoCode, String continent, String location, String date, String totalCases, String newCases, String newCasesSmoothed, String totalDeaths, String newDeaths, String newDeathsSmoothed, String totalCasesPerMillion, String newCasesPerMillion, String newCasesSmoothedPerMillion, String totalDeathsPerMillion, String newDeathsPerMillion, String newDeathsSmoothedPerMillion, String reproductionRate, String icuPatients, String icuPatientsPerMillion, String hospPatients, String hospPatientsPerMillion, String weeklyIcuAdmissions, String weeklyIcuAdmissionsPerMillion, String weeklyHospAdmissions, String weeklyHospAdmissionsPerMillion, String newTests, String totalTests, String totalTestsPerThousand, String newTestsPerThousand, String newTestsSmoothed, String newTestsSmoothedPerThousand, String positiveRate, String testsPerCase, String testsUnits, String totalVaccinations, String peopleVaccinated, String peopleFullyVaccinated, String newVaccinations, String newVaccinationsSmoothed, String totalVaccinationsPerHundred, String peopleVaccinatedPerHundred, String peopleFullyVaccinatedPerHundred, String newVaccinationsSmoothedPerMillion, String stringencyIndex, String population, String populationDensity, String medianAge, String aged65Older, String aged70Older, String gdpPerCapita, String extremePoverty, String cardiovascDeathRate, String diabetesPrevalence, String femaleSmokers, String maleSmokers, String handwashingFacilities, String hospitalBedsPerThousand, String lifeExpectancy, String humanDevelopmentIndex, String excessMortality) {
       this.isoCode = isoCode;
       this.continent = continent;
       this.location = location;
       this.date = date;
       this.totalCases = totalCases;
       this.newCases = newCases;
       this.newCasesSmoothed = newCasesSmoothed;
       this.totalDeaths = totalDeaths;
       this.newDeaths = newDeaths;
       this.newDeathsSmoothed = newDeathsSmoothed;
       this.totalCasesPerMillion = totalCasesPerMillion;
       this.newCasesPerMillion = newCasesPerMillion;
       this.newCasesSmoothedPerMillion = newCasesSmoothedPerMillion;
       this.totalDeathsPerMillion = totalDeathsPerMillion;
       this.newDeathsPerMillion = newDeathsPerMillion;
       this.newDeathsSmoothedPerMillion = newDeathsSmoothedPerMillion;
       this.reproductionRate = reproductionRate;
       this.icuPatients = icuPatients;
       this.icuPatientsPerMillion = icuPatientsPerMillion;
       this.hospPatients = hospPatients;
       this.hospPatientsPerMillion = hospPatientsPerMillion;
       this.weeklyIcuAdmissions = weeklyIcuAdmissions;
       this.weeklyIcuAdmissionsPerMillion = weeklyIcuAdmissionsPerMillion;
       this.weeklyHospAdmissions = weeklyHospAdmissions;
       this.weeklyHospAdmissionsPerMillion = weeklyHospAdmissionsPerMillion;
       this.newTests = newTests;
       this.totalTests = totalTests;
       this.totalTestsPerThousand = totalTestsPerThousand;
       this.newTestsPerThousand = newTestsPerThousand;
       this.newTestsSmoothed = newTestsSmoothed;
       this.newTestsSmoothedPerThousand = newTestsSmoothedPerThousand;
       this.positiveRate = positiveRate;
       this.testsPerCase = testsPerCase;
       this.testsUnits = testsUnits;
       this.totalVaccinations = totalVaccinations;
       this.peopleVaccinated = peopleVaccinated;
       this.peopleFullyVaccinated = peopleFullyVaccinated;
       this.newVaccinations = newVaccinations;
       this.newVaccinationsSmoothed = newVaccinationsSmoothed;
       this.totalVaccinationsPerHundred = totalVaccinationsPerHundred;
       this.peopleVaccinatedPerHundred = peopleVaccinatedPerHundred;
       this.peopleFullyVaccinatedPerHundred = peopleFullyVaccinatedPerHundred;
       this.newVaccinationsSmoothedPerMillion = newVaccinationsSmoothedPerMillion;
       this.stringencyIndex = stringencyIndex;
       this.population = population;
       this.populationDensity = populationDensity;
       this.medianAge = medianAge;
       this.aged65Older = aged65Older;
       this.aged70Older = aged70Older;
       this.gdpPerCapita = gdpPerCapita;
       this.extremePoverty = extremePoverty;
       this.cardiovascDeathRate = cardiovascDeathRate;
       this.diabetesPrevalence = diabetesPrevalence;
       this.femaleSmokers = femaleSmokers;
       this.maleSmokers = maleSmokers;
       this.handwashingFacilities = handwashingFacilities;
       this.hospitalBedsPerThousand = hospitalBedsPerThousand;
       this.lifeExpectancy = lifeExpectancy;
       this.humanDevelopmentIndex = humanDevelopmentIndex;
       this.excessMortality = excessMortality;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIsoCode() {
        return this.isoCode;
    }
    
    public void setIsoCode(String isoCode) {
        this.isoCode = isoCode;
    }
    public String getContinent() {
        return this.continent;
    }
    
    public void setContinent(String continent) {
        this.continent = continent;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTotalCases() {
        return this.totalCases;
    }
    
    public void setTotalCases(String totalCases) {
        this.totalCases = totalCases;
    }
    public String getNewCases() {
        return this.newCases;
    }
    
    public void setNewCases(String newCases) {
        this.newCases = newCases;
    }
    public String getNewCasesSmoothed() {
        return this.newCasesSmoothed;
    }
    
    public void setNewCasesSmoothed(String newCasesSmoothed) {
        this.newCasesSmoothed = newCasesSmoothed;
    }
    public String getTotalDeaths() {
        return this.totalDeaths;
    }
    
    public void setTotalDeaths(String totalDeaths) {
        this.totalDeaths = totalDeaths;
    }
    public String getNewDeaths() {
        return this.newDeaths;
    }
    
    public void setNewDeaths(String newDeaths) {
        this.newDeaths = newDeaths;
    }
    public String getNewDeathsSmoothed() {
        return this.newDeathsSmoothed;
    }
    
    public void setNewDeathsSmoothed(String newDeathsSmoothed) {
        this.newDeathsSmoothed = newDeathsSmoothed;
    }
    public String getTotalCasesPerMillion() {
        return this.totalCasesPerMillion;
    }
    
    public void setTotalCasesPerMillion(String totalCasesPerMillion) {
        this.totalCasesPerMillion = totalCasesPerMillion;
    }
    public String getNewCasesPerMillion() {
        return this.newCasesPerMillion;
    }
    
    public void setNewCasesPerMillion(String newCasesPerMillion) {
        this.newCasesPerMillion = newCasesPerMillion;
    }
    public String getNewCasesSmoothedPerMillion() {
        return this.newCasesSmoothedPerMillion;
    }
    
    public void setNewCasesSmoothedPerMillion(String newCasesSmoothedPerMillion) {
        this.newCasesSmoothedPerMillion = newCasesSmoothedPerMillion;
    }
    public String getTotalDeathsPerMillion() {
        return this.totalDeathsPerMillion;
    }
    
    public void setTotalDeathsPerMillion(String totalDeathsPerMillion) {
        this.totalDeathsPerMillion = totalDeathsPerMillion;
    }
    public String getNewDeathsPerMillion() {
        return this.newDeathsPerMillion;
    }
    
    public void setNewDeathsPerMillion(String newDeathsPerMillion) {
        this.newDeathsPerMillion = newDeathsPerMillion;
    }
    public String getNewDeathsSmoothedPerMillion() {
        return this.newDeathsSmoothedPerMillion;
    }
    
    public void setNewDeathsSmoothedPerMillion(String newDeathsSmoothedPerMillion) {
        this.newDeathsSmoothedPerMillion = newDeathsSmoothedPerMillion;
    }
    public String getReproductionRate() {
        return this.reproductionRate;
    }
    
    public void setReproductionRate(String reproductionRate) {
        this.reproductionRate = reproductionRate;
    }
    public String getIcuPatients() {
        return this.icuPatients;
    }
    
    public void setIcuPatients(String icuPatients) {
        this.icuPatients = icuPatients;
    }
    public String getIcuPatientsPerMillion() {
        return this.icuPatientsPerMillion;
    }
    
    public void setIcuPatientsPerMillion(String icuPatientsPerMillion) {
        this.icuPatientsPerMillion = icuPatientsPerMillion;
    }
    public String getHospPatients() {
        return this.hospPatients;
    }
    
    public void setHospPatients(String hospPatients) {
        this.hospPatients = hospPatients;
    }
    public String getHospPatientsPerMillion() {
        return this.hospPatientsPerMillion;
    }
    
    public void setHospPatientsPerMillion(String hospPatientsPerMillion) {
        this.hospPatientsPerMillion = hospPatientsPerMillion;
    }
    public String getWeeklyIcuAdmissions() {
        return this.weeklyIcuAdmissions;
    }
    
    public void setWeeklyIcuAdmissions(String weeklyIcuAdmissions) {
        this.weeklyIcuAdmissions = weeklyIcuAdmissions;
    }
    public String getWeeklyIcuAdmissionsPerMillion() {
        return this.weeklyIcuAdmissionsPerMillion;
    }
    
    public void setWeeklyIcuAdmissionsPerMillion(String weeklyIcuAdmissionsPerMillion) {
        this.weeklyIcuAdmissionsPerMillion = weeklyIcuAdmissionsPerMillion;
    }
    public String getWeeklyHospAdmissions() {
        return this.weeklyHospAdmissions;
    }
    
    public void setWeeklyHospAdmissions(String weeklyHospAdmissions) {
        this.weeklyHospAdmissions = weeklyHospAdmissions;
    }
    public String getWeeklyHospAdmissionsPerMillion() {
        return this.weeklyHospAdmissionsPerMillion;
    }
    
    public void setWeeklyHospAdmissionsPerMillion(String weeklyHospAdmissionsPerMillion) {
        this.weeklyHospAdmissionsPerMillion = weeklyHospAdmissionsPerMillion;
    }
    public String getNewTests() {
        return this.newTests;
    }
    
    public void setNewTests(String newTests) {
        this.newTests = newTests;
    }
    public String getTotalTests() {
        return this.totalTests;
    }
    
    public void setTotalTests(String totalTests) {
        this.totalTests = totalTests;
    }
    public String getTotalTestsPerThousand() {
        return this.totalTestsPerThousand;
    }
    
    public void setTotalTestsPerThousand(String totalTestsPerThousand) {
        this.totalTestsPerThousand = totalTestsPerThousand;
    }
    public String getNewTestsPerThousand() {
        return this.newTestsPerThousand;
    }
    
    public void setNewTestsPerThousand(String newTestsPerThousand) {
        this.newTestsPerThousand = newTestsPerThousand;
    }
    public String getNewTestsSmoothed() {
        return this.newTestsSmoothed;
    }
    
    public void setNewTestsSmoothed(String newTestsSmoothed) {
        this.newTestsSmoothed = newTestsSmoothed;
    }
    public String getNewTestsSmoothedPerThousand() {
        return this.newTestsSmoothedPerThousand;
    }
    
    public void setNewTestsSmoothedPerThousand(String newTestsSmoothedPerThousand) {
        this.newTestsSmoothedPerThousand = newTestsSmoothedPerThousand;
    }
    public String getPositiveRate() {
        return this.positiveRate;
    }
    
    public void setPositiveRate(String positiveRate) {
        this.positiveRate = positiveRate;
    }
    public String getTestsPerCase() {
        return this.testsPerCase;
    }
    
    public void setTestsPerCase(String testsPerCase) {
        this.testsPerCase = testsPerCase;
    }
    public String getTestsUnits() {
        return this.testsUnits;
    }
    
    public void setTestsUnits(String testsUnits) {
        this.testsUnits = testsUnits;
    }
    public String getTotalVaccinations() {
        return this.totalVaccinations;
    }
    
    public void setTotalVaccinations(String totalVaccinations) {
        this.totalVaccinations = totalVaccinations;
    }
    public String getPeopleVaccinated() {
        return this.peopleVaccinated;
    }
    
    public void setPeopleVaccinated(String peopleVaccinated) {
        this.peopleVaccinated = peopleVaccinated;
    }
    public String getPeopleFullyVaccinated() {
        return this.peopleFullyVaccinated;
    }
    
    public void setPeopleFullyVaccinated(String peopleFullyVaccinated) {
        this.peopleFullyVaccinated = peopleFullyVaccinated;
    }
    public String getNewVaccinations() {
        return this.newVaccinations;
    }
    
    public void setNewVaccinations(String newVaccinations) {
        this.newVaccinations = newVaccinations;
    }
    public String getNewVaccinationsSmoothed() {
        return this.newVaccinationsSmoothed;
    }
    
    public void setNewVaccinationsSmoothed(String newVaccinationsSmoothed) {
        this.newVaccinationsSmoothed = newVaccinationsSmoothed;
    }
    public String getTotalVaccinationsPerHundred() {
        return this.totalVaccinationsPerHundred;
    }
    
    public void setTotalVaccinationsPerHundred(String totalVaccinationsPerHundred) {
        this.totalVaccinationsPerHundred = totalVaccinationsPerHundred;
    }
    public String getPeopleVaccinatedPerHundred() {
        return this.peopleVaccinatedPerHundred;
    }
    
    public void setPeopleVaccinatedPerHundred(String peopleVaccinatedPerHundred) {
        this.peopleVaccinatedPerHundred = peopleVaccinatedPerHundred;
    }
    public String getPeopleFullyVaccinatedPerHundred() {
        return this.peopleFullyVaccinatedPerHundred;
    }
    
    public void setPeopleFullyVaccinatedPerHundred(String peopleFullyVaccinatedPerHundred) {
        this.peopleFullyVaccinatedPerHundred = peopleFullyVaccinatedPerHundred;
    }
    public String getNewVaccinationsSmoothedPerMillion() {
        return this.newVaccinationsSmoothedPerMillion;
    }
    
    public void setNewVaccinationsSmoothedPerMillion(String newVaccinationsSmoothedPerMillion) {
        this.newVaccinationsSmoothedPerMillion = newVaccinationsSmoothedPerMillion;
    }
    public String getStringencyIndex() {
        return this.stringencyIndex;
    }
    
    public void setStringencyIndex(String stringencyIndex) {
        this.stringencyIndex = stringencyIndex;
    }
    public String getPopulation() {
        return this.population;
    }
    
    public void setPopulation(String population) {
        this.population = population;
    }
    public String getPopulationDensity() {
        return this.populationDensity;
    }
    
    public void setPopulationDensity(String populationDensity) {
        this.populationDensity = populationDensity;
    }
    public String getMedianAge() {
        return this.medianAge;
    }
    
    public void setMedianAge(String medianAge) {
        this.medianAge = medianAge;
    }
    public String getAged65Older() {
        return this.aged65Older;
    }
    
    public void setAged65Older(String aged65Older) {
        this.aged65Older = aged65Older;
    }
    public String getAged70Older() {
        return this.aged70Older;
    }
    
    public void setAged70Older(String aged70Older) {
        this.aged70Older = aged70Older;
    }
    public String getGdpPerCapita() {
        return this.gdpPerCapita;
    }
    
    public void setGdpPerCapita(String gdpPerCapita) {
        this.gdpPerCapita = gdpPerCapita;
    }
    public String getExtremePoverty() {
        return this.extremePoverty;
    }
    
    public void setExtremePoverty(String extremePoverty) {
        this.extremePoverty = extremePoverty;
    }
    public String getCardiovascDeathRate() {
        return this.cardiovascDeathRate;
    }
    
    public void setCardiovascDeathRate(String cardiovascDeathRate) {
        this.cardiovascDeathRate = cardiovascDeathRate;
    }
    public String getDiabetesPrevalence() {
        return this.diabetesPrevalence;
    }
    
    public void setDiabetesPrevalence(String diabetesPrevalence) {
        this.diabetesPrevalence = diabetesPrevalence;
    }
    public String getFemaleSmokers() {
        return this.femaleSmokers;
    }
    
    public void setFemaleSmokers(String femaleSmokers) {
        this.femaleSmokers = femaleSmokers;
    }
    public String getMaleSmokers() {
        return this.maleSmokers;
    }
    
    public void setMaleSmokers(String maleSmokers) {
        this.maleSmokers = maleSmokers;
    }
    public String getHandwashingFacilities() {
        return this.handwashingFacilities;
    }
    
    public void setHandwashingFacilities(String handwashingFacilities) {
        this.handwashingFacilities = handwashingFacilities;
    }
    public String getHospitalBedsPerThousand() {
        return this.hospitalBedsPerThousand;
    }
    
    public void setHospitalBedsPerThousand(String hospitalBedsPerThousand) {
        this.hospitalBedsPerThousand = hospitalBedsPerThousand;
    }
    public String getLifeExpectancy() {
        return this.lifeExpectancy;
    }
    
    public void setLifeExpectancy(String lifeExpectancy) {
        this.lifeExpectancy = lifeExpectancy;
    }
    public String getHumanDevelopmentIndex() {
        return this.humanDevelopmentIndex;
    }
    
    public void setHumanDevelopmentIndex(String humanDevelopmentIndex) {
        this.humanDevelopmentIndex = humanDevelopmentIndex;
    }
    public String getExcessMortality() {
        return this.excessMortality;
    }
    
    public void setExcessMortality(String excessMortality) {
        this.excessMortality = excessMortality;
    }

//--------------------------------------------------------------

    public Covid(Integer id, String isoCode, String continent, String location, String date, String totalCases, String totalDeaths, String totalTests, String totalVaccinations) {
        this.id = id;
        this.isoCode = isoCode;
        this.continent = continent;
        this.location = location;
        this.date = date;
        this.totalCases = totalCases;
        this.totalDeaths = totalDeaths;
        this.totalTests = totalTests;
        this.totalVaccinations = totalVaccinations;
    }
    
    //Liste des enregistrements
    public static List  listCovids(){
      
        
      SessionFactory sessionFactory = NewHibernateUtil.getSessionFactory();
      Session session = sessionFactory.openSession();
      org.hibernate.Transaction tx = session.beginTransaction();
      Query query=  session.createQuery("from Covid");
      tx.commit();
      List results = query.list();
  
  return results ;

  /*    
        Session sessionHiber =
NewHibernateUtil.getSessionFactory().getCurrentSession();
sessionHiber.beginTransaction();
Query query=  sessionHiber.createQuery("SELECT COUNT(*) from Covid");
sessionHiber.getTransaction().commit();
List results = query.list();
*/  
  }
    
    //liste des enregistrement filtée
    public static List  listCovidsFiltree(String c, String l, boolean h){
        String s = "from Covid";
        if(c.equals("ALL") && l.equals("ALL")){
            if(!h){
                s="select isoCode, continent, distinct location, date, totalCases, totalDeaths, totalTests, totalVaccinations from Covid";
            }else{
                s="select isoCode, continent, location, date, totalCases, totalDeaths, totalTests, totalVaccinations from Covid";
            }
        }
        else if(c.equals("ALL") && (!(l.equals("ALL")))){
            if(!h){
                s="select isoCode, continent, distinct location, date, totalCases, totalDeaths, totalTests, totalVaccinations from Covid where location = '"+l+"'";
            }else{
                 s="select isoCode, continent, location, date, totalCases, totalDeaths, totalTests, totalVaccinations from Covid where location = '"+l+"'";
            }
        }
        if( (!(c.equals("ALL"))) && l.equals("ALL")){
            if(!h){
                 s="select isoCode, continent, distinct location, date, totalCases, totalDeaths, totalTests, totalVaccinations from Covid where continent = '"+c+"'";
            }else{
                 s="select isoCode, continent,  location, date, totalCases, totalDeaths, totalTests, totalVaccinations from Covid where continent = '"+c+"'";

            }
        }
        if((!(c.equals("ALL"))) && (!(l.equals("ALL")))){
            if(!h){
                s="select isoCode, continent, distinct location, date, totalCases, totalDeaths, totalTests, totalVaccinations from Covid where location = '"+l+"'";
            }else{
                 s="select isoCode, continent,  location, date, totalCases, totalDeaths, totalTests, totalVaccinations from Covid where location = '"+l+"'";
            }
        }
        
      SessionFactory sessionFactory = NewHibernateUtil.getSessionFactory();
      Session session = sessionFactory.openSession();
      org.hibernate.Transaction tx = session.beginTransaction();
      Query query=  session.createQuery(s);
      tx.commit();
      List results = query.list();
  
  return results ;
    }
    
    public static List  listByLocation(String l){
        String s;
        
        if(l.equals("ALL")){
                 s="from Covid";
            }else{
                s="from Covid where location = '"+l+"'";
            }
      SessionFactory sessionFactory = NewHibernateUtil.getSessionFactory();
      Session session = sessionFactory.openSession();
      org.hibernate.Transaction tx = session.beginTransaction();
      Query query=  session.createQuery(s);
      tx.commit();
      List results = query.list();
  
  return results ;
    }
    
    
    public static List  listByContinents(String c){
        String s;
        
        if(c.equals("ALL")){
                 s="from Covid";
            }else{
                 s="from Covid where continent = '"+c+"'";

            }
        
        
      SessionFactory sessionFactory = NewHibernateUtil.getSessionFactory();
      Session session = sessionFactory.openSession();
      org.hibernate.Transaction tx = session.beginTransaction();
      Query query=  session.createQuery(s);
      tx.commit();
      List results = query.list();
  
  return results ;
    }
    
 //liste des continents
    public static List  listContinents(){
      
        
      SessionFactory sessionFactory = NewHibernateUtil.getSessionFactory();
      Session session = sessionFactory.openSession();
      org.hibernate.Transaction tx = session.beginTransaction();
      Query query=  session.createQuery("select distinct continent from Covid");
      tx.commit();
      List results = query.list();
  
  return results ;
    }
  //liste des locations
    public static List  listLocations(String c){
      String s;
      if(c.equals("ALL")){
          s = "select distinct location from Covid";
      }else{
          s = "select distinct location from Covid where continent like '"+c+"'";
      }    
        
      SessionFactory sessionFactory = NewHibernateUtil.getSessionFactory();
      Session session = sessionFactory.openSession();
      org.hibernate.Transaction tx = session.beginTransaction();
      Query query=  session.createQuery(s);
      tx.commit();
      List results = query.list();
       
  
  return results ;
    } 
    
     //liste des iso_codes
    public static List  ListisoCodes(){
      
        
      SessionFactory sessionFactory = NewHibernateUtil.getSessionFactory();
      Session session = sessionFactory.openSession();
      org.hibernate.Transaction tx = session.beginTransaction();
      Query query=  session.createQuery("select isoCode from Covid");
      tx.commit();
      List results = query.list();
  
  return results ;
    } 
    
    
    


}


